### ISSUE TITLE
A PDF Version

### ISSUE THREAD

**Issue by ahmedsadman** [in28minutes/java-cheat-sheet#2]
Would you please consider adding a PDF version of this cheat sheet?

**Comment by satyana3** [comment]
.

**Comment by xianyuzhang0709** [comment]
> Would you please consider adding a PDF version of this cheat sheet?

you can print the web page in PDF.

**Comment by in28minutes** [comment]
You can go to https://github.com/in28minutes/java-cheat-sheet/blob/master/README.md and File Print and Print it as PDF.
